config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }
  resources :users, only: %i[index show]
  resources :events, only: %i[index new create show destroy edit update]
  resources :invitations, only: %i[create destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :date, presence: true
  validates :location, presence: true

  belongs_to :creator, class_name: 'User'

  has_many :invitations, dependent: :delete_all
  has_many :attendees, through: :invitations , dependent: :delete_all

  scope :past, -> { where('date <= ?', Date.current) }
  scope :upcoming, -> { where('date > ?', Date.current) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User'

  # https://apidock.com/rails/ActiveRecord/Validations/ClassMethods/validates_uniqueness_of
  validates_uniqueness_of :event_id, scope: %i[attendee_id]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :events_created, class_name: 'Event', foreign_key: 'creator_id', dependent: :nullify

  # https://stackoverflow.com/questions/4632408/understanding-source-option-of-has-one-has-many-through-of-rails
  has_many :invitations, foreign_key: 'attendee_id', dependent: :delete_all
  has_many :events_invited, through: :invitations, source: :event, dependent: :delete_all
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_event, only: %i[show destroy edit update]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events_created.new(event_params)
    if @event.save
      redirect_to events_path, notice: "You created #{event_params[:name]} event!"
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @host = @event.creator
    @attendees = @event.attendees
  end

  def destroy
    @event.destroy

    redirect_to events_path, notice: 'You deleted the event!'
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  protected

  def event_params
    params.expect(event: %i[name date location])
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    event = Event.find(params[:event])
    @inv = Invitation.create(event: event, attendee: current_user)

    redirect_to(event_path(params[:event]))
  end

  def destroy
    @inv = Invitation.find_by(event: params[:id], attendee: current_user)
    return if @inv.nil?

    @inv.destroy
    redirect_to request.original_url, notice: 'Invitation declined!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @invited_events = @user.events_invited
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event/index.html.erb
<h1>Event#index</h1>
<p>Find me in app/views/event/index.html.erb</p>

<%=render "shared/session_handler"%>
<%= link_to "See all users", users_path%>


<h2>All Events</h2>
<%=link_to "Create event",  new_event_path%>
<div class="calendar">
<%@events.sort_by(&:date).each do |event|%>
    <div class="event">
        <h3><%= event.name %></h3>
        <div><%= event.date %></div>
        <div><%= event.location %></div>
    </div>
<%end%>
</div>

app/views/events/_event.html.erb
<div class="event">
    <h3><%= event.name.capitalize %></h3>
    <div><%= event.date %></div>
    <div><%= event.location.capitalize %></div>
    <% unless current_page?(event_path(event)) %>
        <div><%= link_to "Link", event_path(event)%></div>
    <%end%>
    <%if current_user != event.creator%>
        <div>
            <div>You are invited:</div>
            <%=button_to "Accept", controller:"invitations", action: "create", params:{event:event} %>
            <%#the route is invitation DELETE /invitations/:id(.:format) invitations#destroy %>
            <%=button_to "Decline", {controller: :invitations, action: "destroy", id:event},method: :delete %>
        </div>
    <%else%>
        <div>
            <div>You are the creator:</div>
            <%=button_to "Edit Event", edit_event_path(event), method: :get %>

            <%=button_to "Delete Event", {controller: :events, action: "destroy", id:event},method: :delete , data: {confirm: "Are you sure you want to delete the event?" }%>
        </div>
    <%end%>
</div>

app/views/events/_form.html.erb
<% all_errors = @event.errors.as_json if @event.errors.any? %>
<%= form_with model: @event do |form|%>
    <div>
        <%=form.label :name, "Event Name:"%>
        <%=form.text_field :name%>
        <%=all_errors[:name].first unless all_errors.nil?%>
    </div>
    <div>
        <%=form.label :date, "Event Date:"%>
        <%=form.date_field :date%>
        <%=all_errors[:date].first unless all_errors.nil?%>

    </div>
    <div>
        <%=form.label :location, "Event Location:"%>
        <%=form.text_field :location%>
        <%=all_errors[:location].first unless all_errors.nil?%>
    </div>
    <%=form.submit%>
<%end%>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

<%=render "shared/session_handler"%>

<h1>Edit Event</h1>

<%=render "form"%>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

<%=render "shared/session_handler"%>
<%=link_to "See all users", users_path%>


<h2>All Events</h2>
<%=link_to "Create event",  new_event_path %>
<div class="calendar">
<%@events.sort_by(&:date).each do |event|%>
    <%=render event %>
<%end%>
</div>

<h3>Total:<%=@events.count%></h3>
<div><strong>Upcoming:</strong><%=Event.upcoming.count%></div>
<div><strong>Pasted:</strong><%=Event.past.count%></div>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

<%=render "shared/session_handler"%>

<h1>Create New Event</h1>

<%=render "form"%>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

<%=render "shared/session_handler"%>
<%=link_to "Events Feed", events_path%>
<%=render @event%>

<h2>Host: <%=render @host%></h2>

<h2>List of Attendees:</h2>
<%unless @attendees.empty?%>
<ul>
    <%@attendees.each do |attendee|%>
    <li><%=render attendee %></li>
    <%end%>
</ul>
<%else%>
<p>No attendees yet</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_list_events.html.erb
<%unless list_events.empty?%>
    <ul>        
        <%list_events.each do |event|%>
            <li><%="#{event.name.capitalize} #{event.date if defined?(print_date) && print_date} "%> <%= link_to "*", event_path(event.id) %></li>
        <%end%>
    </ul>
<%else%>
    <div>-</div>
<%end%>

app/views/shared/_session_handler.html.erb
<div class="session_handler">
    <%if user_signed_in?%>
        <%user_name = current_user.name.capitalize%>
        <div>Hello, <%=user_name%><%= link_to " Go to profile", user_path(current_user.id)%></div>
    <div>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"as-link"%>
    </div>
    <%else%>
        <div>Hello, Stranger</div>
        <%=link_to("Log in", new_user_session_path)%>
    <%end%>
</div>

app/views/users/_user.html.erb
<%=user.name.capitalize%>
<%# https://guides.rubyonrails.org/layouts_and_rendering.html#passing-local-variables %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%=render "shared/session_handler"%>
<%=link_to "Events Feed", events_path%>

<h2>All current users of the app [<%=@users.size%>]</h2>
<%@users.each do |user|%>
<p>-> <%=link_to user.name.capitalize, user_path(user.id)%></p>
<%end%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%=link_to "Events Feed", events_path%>

<%if current_user == @user%>
<h2>You are seeing your profile</h2>

<%else%>
<h2>You are seeing <%=@user.name.capitalize%> profile</h2>
<%end%>

<%=image_tag("logo.jpg", alt:"test text")%>

<h3>All events created by <%=@user.name.capitalize%>:</h3>
<%= render partial: "shared/list_events", object:@user.events_created, print_date: false%>


<h3>Events to attend</h3>
<%future_events = @invited_events.where("date > :current_date", {current_date: Date.current})%>
<%=render partial:"shared/list_events", object: future_events %>


<h3>Events attended</h3>
<%past_events = @invited_events.where("date <= :current_date", {current_date: Date.current})%>
<%=render partial:"shared/list_events", object: past_events%> 